version: "3.9"
services:
  app:
    build: .
    container_name: tasktest-app
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: serverName=tasktest
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    depends_on:
      - db
  web:
    image: nginx:1.27-alpine
    container_name: tasktest-web
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: tasktest-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: